sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install coveralls coverage django-setuptest responses --use-wheel --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - DJANGO_SETTINGS_MODULE=test_settings coverage run --source='google_analytics' `which django-admin.py` test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    secure: O0feip8iJtd8Pulu2m9qcAg2yqwBUe5FsvYSaWTJke8a9oiS4xGittATKqbxUZNvFjHpbS79V2032IPDs+oNePwotSavPiKeSF1xNxAaeGuEH7nFuaYQ4/RzLpHHYU3KT61sa32U+bdH3AoDvAb/5MzlLucTVGLEuCUpHXLhcx0=
  on:
    tags: true
    all_branches: true
